common.datasource.username=aashutosh
common.datasource.password=Bank@123
common.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

demography.datasource.url=jdbc:mysql://localhost:3306/core
payments.datasource.url=jdbc:mysql://localhost:3306/payments
security.datasource.url=jdbc:mysql://localhost:3306/datasecurity
