  #spring.application.name=core
server:
  port: 8084
spring:
  application:
    name: core-service
  datasource:
    url: jdbc:mysql://localhost:3306/core
    username: aashutosh
    password: Bank@123
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true